pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building.. cpp'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing.. cpp'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying.... cpp'
            }
        }
    }
}