pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building.. python'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing.. python'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying.... python'
            }
        }
    }
}